// Generated by tools/gen_z80.py -- do not edit.
// Regenerate with:  python tools/gen_z80.py

localparam int UW     = 51;   // micro-op width
localparam int UROM_N = 357;  // micro-op count
localparam int UPCW   = 9;   // micro-PC width

// micro-op field slices: read one as uw[UFL_x +: UFW_x]
localparam int UFL_BUS  =  0, UFW_BUS  = 3;
localparam int UFL_TX   =  3, UFW_TX   = 3;
localparam int UFL_ASRC =  6, UFW_ASRC = 4;
localparam int UFL_AINC = 10, UFW_AINC = 2;
localparam int UFL_DS   = 12, UFW_DS   = 5;
localparam int UFL_DD   = 17, UFW_DD   = 5;
localparam int UFL_PD   = 22, UFW_PD   = 5;
localparam int UFL_WSRC = 27, UFW_WSRC = 5;
localparam int UFL_ALU  = 32, UFW_ALU  = 6;
localparam int UFL_FW   = 38, UFW_FW   = 1;
localparam int UFL_EOP  = 39, UFW_EOP  = 5;
localparam int UFL_CTL  = 44, UFW_CTL  = 4;
localparam int UFL_NX   = 48, UFW_NX   = 3;


// interrupt entry points
localparam int UENT_NMI = 345;
localparam int UENT_IM1 = 348;
localparam int UENT_IM2 = 352;

// BUS
localparam logic [2:0] BUS_NONE = 0;
localparam logic [2:0] BUS_INT = 1;
localparam logic [2:0] BUS_MR = 2;
localparam logic [2:0] BUS_MW = 3;
localparam logic [2:0] BUS_IOR = 4;
localparam logic [2:0] BUS_IOW = 5;

// ASRC
localparam logic [3:0] ASRC_PC = 0;
localparam logic [3:0] ASRC_SP = 1;
localparam logic [3:0] ASRC_HL = 2;
localparam logic [3:0] ASRC_BC = 3;
localparam logic [3:0] ASRC_DE = 4;
localparam logic [3:0] ASRC_WZ = 5;
localparam logic [3:0] ASRC_RP = 6;
localparam logic [3:0] ASRC_AZ = 7;
localparam logic [3:0] ASRC_HLR = 8;
localparam logic [3:0] ASRC_DER = 9;
localparam logic [3:0] ASRC_RST = 10;
localparam logic [3:0] ASRC_BCR = 11;
localparam logic [3:0] ASRC_SPP1 = 12;

// AINC
localparam logic [1:0] AINC_NONE = 0;
localparam logic [1:0] AINC_POSTINC = 1;
localparam logic [1:0] AINC_PREDEC = 2;
localparam logic [1:0] AINC_POSTDEC = 3;

// DAT
localparam logic [4:0] DAT_B = 0;
localparam logic [4:0] DAT_C = 1;
localparam logic [4:0] DAT_D = 2;
localparam logic [4:0] DAT_E = 3;
localparam logic [4:0] DAT_H = 4;
localparam logic [4:0] DAT_L = 5;
localparam logic [4:0] DAT_DIN = 6;
localparam logic [4:0] DAT_A = 7;
localparam logic [4:0] DAT_F = 8;
localparam logic [4:0] DAT_W = 9;
localparam logic [4:0] DAT_Z = 10;
localparam logic [4:0] DAT_I = 11;
localparam logic [4:0] DAT_R = 12;
localparam logic [4:0] DAT_SPH = 13;
localparam logic [4:0] DAT_SPL = 14;
localparam logic [4:0] DAT_PCH = 15;
localparam logic [4:0] DAT_PCL = 16;
localparam logic [4:0] DAT_HRAW = 17;
localparam logic [4:0] DAT_LRAW = 18;
localparam logic [4:0] DAT_RLO = 19;
localparam logic [4:0] DAT_RHI = 20;
localparam logic [4:0] DAT_RLOR = 21;
localparam logic [4:0] DAT_RHIR = 22;
localparam logic [4:0] DAT_RPH = 23;
localparam logic [4:0] DAT_RPL = 24;
localparam logic [4:0] DAT_RQH = 25;
localparam logic [4:0] DAT_RQL = 26;
localparam logic [4:0] DAT_TMP = 27;
localparam logic [4:0] DAT_ZERO = 28;
localparam logic [4:0] DAT_RLOT = 30;
localparam logic [4:0] DAT_NONE = 31;

// ALU
localparam logic [5:0] ALU_NOP = 0;
localparam logic [5:0] ALU_ADD = 1;
localparam logic [5:0] ALU_ADC = 2;
localparam logic [5:0] ALU_SUB = 3;
localparam logic [5:0] ALU_SBC = 4;
localparam logic [5:0] ALU_AND = 5;
localparam logic [5:0] ALU_XOR = 6;
localparam logic [5:0] ALU_OR = 7;
localparam logic [5:0] ALU_CP = 8;
localparam logic [5:0] ALU_INC = 9;
localparam logic [5:0] ALU_DEC = 10;
localparam logic [5:0] ALU_RLC = 11;
localparam logic [5:0] ALU_RRC = 12;
localparam logic [5:0] ALU_RL = 13;
localparam logic [5:0] ALU_RR = 14;
localparam logic [5:0] ALU_SLA = 15;
localparam logic [5:0] ALU_SRA = 16;
localparam logic [5:0] ALU_SLL = 17;
localparam logic [5:0] ALU_SRL = 18;
localparam logic [5:0] ALU_BIT = 19;
localparam logic [5:0] ALU_RES = 20;
localparam logic [5:0] ALU_SET = 21;
localparam logic [5:0] ALU_RLCA = 22;
localparam logic [5:0] ALU_RRCA = 23;
localparam logic [5:0] ALU_RLA = 24;
localparam logic [5:0] ALU_RRA = 25;
localparam logic [5:0] ALU_DAA = 26;
localparam logic [5:0] ALU_CPL = 27;
localparam logic [5:0] ALU_SCF = 28;
localparam logic [5:0] ALU_CCF = 29;
localparam logic [5:0] ALU_NEG = 30;
localparam logic [5:0] ALU_INF = 31;
localparam logic [5:0] ALU_LDAIR = 32;
localparam logic [5:0] ALU_RLDM = 33;
localparam logic [5:0] ALU_RLDA = 34;
localparam logic [5:0] ALU_RRDM = 35;
localparam logic [5:0] ALU_RRDA = 36;
localparam logic [5:0] ALU_BITM = 37;

// EOP
localparam logic [4:0] EOP_NONE = 0;
localparam logic [4:0] EOP_INC_RP = 1;
localparam logic [4:0] EOP_DEC_RP = 2;
localparam logic [4:0] EOP_ADD_HL = 3;
localparam logic [4:0] EOP_ADC_HL = 4;
localparam logic [4:0] EOP_SBC_HL = 5;
localparam logic [4:0] EOP_JR = 6;
localparam logic [4:0] EOP_DISP = 7;
localparam logic [4:0] EOP_HL_WZ = 8;
localparam logic [4:0] EOP_PC_WZ = 9;
localparam logic [4:0] EOP_PC_HL = 11;
localparam logic [4:0] EOP_SP_HL = 12;
localparam logic [4:0] EOP_PC_RST = 13;
localparam logic [4:0] EOP_LDI = 14;
localparam logic [4:0] EOP_LDD = 15;
localparam logic [4:0] EOP_CPI = 16;
localparam logic [4:0] EOP_CPD = 17;
localparam logic [4:0] EOP_INI = 18;
localparam logic [4:0] EOP_IND = 19;
localparam logic [4:0] EOP_OUTI = 20;
localparam logic [4:0] EOP_OUTD = 21;
localparam logic [4:0] EOP_REPEAT = 22;
localparam logic [4:0] EOP_WZ_BC_INC = 23;
localparam logic [4:0] EOP_WZ_A1 = 24;
localparam logic [4:0] EOP_WZ_WRA = 25;
localparam logic [4:0] EOP_WZ_HL1 = 27;
localparam logic [4:0] EOP_DEC_B = 28;

// CTL
localparam logic [3:0] CTL_NONE = 0;
localparam logic [3:0] CTL_EX_DE_HL = 1;
localparam logic [3:0] CTL_EXX = 2;
localparam logic [3:0] CTL_EX_AF = 3;
localparam logic [3:0] CTL_DI = 4;
localparam logic [3:0] CTL_EI = 5;
localparam logic [3:0] CTL_SET_IM = 6;
localparam logic [3:0] CTL_HALT = 7;
localparam logic [3:0] CTL_RETN = 8;
localparam logic [3:0] CTL_SET_P = 9;

// FW
localparam logic [0:0] FW_NONE = 0;
localparam logic [0:0] FW_ALU = 1;

// NX
localparam logic [2:0] NX_NEXT = 0;
localparam logic [2:0] NX_END = 1;
localparam logic [2:0] NX_CC = 2;
localparam logic [2:0] NX_NZ_B = 3;
localparam logic [2:0] NX_CCJ = 4;
localparam logic [2:0] NX_BLK = 5;

